### ISSUE TITLE
account icon, sign up and login not working

### ISSUE THREAD

**Issue by nodarik** [ColorlibHQ/Fashe#11]
As the title says its account icon is not working, its linked to the homepage not to the login page

**Comment by csmithq2** [comment]
Can we please hurry up and get this fixed before the biggest shopping day of the year! Fashe on mobile is a disaster. But it looks beautiful on a desktop. Most of my traffic uses mobile, this needs to be fixed.

**Comment by cristian-e** [comment]
This is no longer an issue. The account icon links to `/account/login`.

**Comment by cristianraiber** [comment]
Was probably fixed by @giucu91 in his previous update. 

@csmithq2 - if the issue persists, please reply here.
