### ISSUE TITLE
Can i change the Mobile Collection Grid to 4 Images on screen instead of scrolling through the products one by one ?

### ISSUE THREAD

**Issue by mawahebsaeed** [ColorlibHQ/Fashe#14]
Can i change the Mobile Collection Grid to 4 Images on screen instead of scrolling through the products one by one ?

**Comment by mawahebsaeed** [comment]
Can i change the Mobile Collection Grid to 4 Images on screen instead of scrolling through the products one by one ?

**Comment by cristianraiber** [comment]
@mawahebsaeed - I've deleted your duplicate comment
@cristian-e - please check if this is possible and reply here once you've reached a conclusion.

**Comment by cristianraiber** [comment]
@cristian-e - yeah, that actually makes sense. This is mostly a design decision, what @mawahebsaeed reported so I'm going to be closing this ticket as it's not functionality related.
