### ISSUE TITLE
Duplicate cart content

### ISSUE THREAD

**Issue by cristian-e** [ColorlibHQ/Fashe#15]
Using `Header Layout - Design 2`, when adding an item to the cart, the content is added twice. 
This issue is ocurring on all screen sizes

![3](https://user-images.githubusercontent.com/43263346/51538927-2dc12280-1e5b-11e9-8460-4bc29ef6a25d.PNG)

**Comment by sicdigital** [comment]
I also have this fixed on my local version. I'll push a PR for this also.

**Comment by cristianraiber** [comment]
@sicdigital - I think @cristian-e has already fixed this. He just reported the issue here so we'll have evidence of what was fixed, by who, and when.

**Comment by cristian-e** [comment]
This issue has been fixed with the latest commit.
