### ISSUE TITLE
Single product page, add to cart

### ISSUE THREAD

**Issue by cristian-e** [ColorlibHQ/Fashe#16]
When you add an item to the cart (on a single product page), clicking on the cart icon, on mobile, will reveal that the cart is empty (even though you added a product).

![8985](https://user-images.githubusercontent.com/43263346/51539868-bccf3a00-1e5d-11e9-8fc5-ae686d648905.PNG)

**Comment by sicdigital** [comment]
I actually fixed this on a version I have, it's because the jquery selectors are using duplicate IDs. I'll add a PR that fixes it.

**Comment by cristianraiber** [comment]
@sicdigital - I think @cristian-e has already fixed this. He just reported the issue here so we'll have evidence of what was fixed, by who, and when.

**Comment by sicdigital** [comment]
ah ok, I didn't realize he was the dev, but I did fix this on my version also, both the duplication of the cart contents and the mobile cart not updating are because of the same issue -- using an ID for a jquery selector only selects the first item found in the document.

**Comment by cristianraiber** [comment]
@sicdigital - feel free to also create a PR. If @cristian-e hasn't had the time to actually fix it, he'll merge your PR :) Otherwise, it'll be closed.

However, I do want to take a few moments to thank you for pitching in :) Highly appreciated!

**Comment by sicdigital** [comment]
#18 - is ready for review, no problem, thanks for making a cool theme! :)
