### ISSUE TITLE
No where to log out

### ISSUE THREAD

**Issue by sicdigital** [ColorlibHQ/Fashe#17]
The theme doesn't have any way for a logged in user to log out.

**Comment by cristianraiber** [comment]
@sicdigital - nice catch :)

**Comment by sicdigital** [comment]
It makes sense to add a dropdown to the top right icon that can contain a custom navigation. This would be a good place to add logout/my account/ my addresses / my orders.

**Comment by cristianraiber** [comment]
@cristian-e - please add this to your to-do list as well :)

**Comment by sicdigital** [comment]
This is what I did for my store. I use different icons than the default, but I'm using the same dropdown structure as the cart and added a simple link for logout. It could probably be extended to include a custom menu here, but this works for me for now. I can submit a PR for this on the default theme if you like.

![logged-in-customer](https://user-images.githubusercontent.com/476204/51569744-e8085800-1e62-11e9-8af0-a771d56c010f.png)
![not-logged-in-customer](https://user-images.githubusercontent.com/476204/51569745-e8085800-1e62-11e9-93d2-67c1251743ec.png)

**Comment by cristian-e** [comment]
The latest commit adds this link in the header:
![91212](https://user-images.githubusercontent.com/43263346/51611280-8bbb3c00-1f27-11e9-920e-7fc696907b59.PNG)
 and also on the account page:
![31313](https://user-images.githubusercontent.com/43263346/51611322-a2fa2980-1f27-11e9-9926-976bb2e2d66c.PNG)
