### ISSUE TITLE
Product page

### ISSUE THREAD

**Issue by nodarik** [ColorlibHQ/Fashe#2]
The product page has some problems like:
no description is visible, 
no add to cart button
no product variation option

link with a problem:
https://www.piotrman.com/products/boxy-t-shirt-with-roll-sleeve-detail

reported here:
https://colorlib.com/wp/forums/topic/fashe/

**Comment by Petterholm** [comment]
Still waiting for a reply here.

**Comment by Raghav17** [comment]
Please help, product variation images is not working for me.

**Comment by giucu91** [comment]
Hello, the product variation was fixed but the other issues I can't reproduce them. Here is a link : 
https://fashe-stheme.myshopify.com/products/t-shirt
