### ISSUE TITLE
"Apply coupon" button & others

### ISSUE THREAD

**Issue by cboursier** [ColorlibHQ/Fashe#25]
Hello !

First of all i would like to report that on the cart, the button to apply a coupon is on commentary.

`          <div class="size12 trans-0-4 m-t-10 m-b-10 m-r-10">`
           `  <!-- Button -->`
            ` <!-- <button class="flex-c-m sizefull bg4 bo-rad-5 hov1 s-text1 trans-0-4">`
		` 		Apply coupon`
		` 	</button> -->`
        `   </div>`
And not working, clicking on this button only redirect to the payment page :)

I was also wondering how we are suposed to translate the sweetalert message like this one :
![Capture](https://user-images.githubusercontent.com/39302648/54759990-798c1000-4bef-11e9-95ca-ad197217d264.PNG)

Thanks for your help
Best regards

**Comment by cboursier** [comment]
Hello, 
Sorry to figure out that late but i tried different things and the apply coupon button works great.
It apply the code reduction on the cart but it also so a redirection on the paiment process page which is maybe not very smooth. But actualy the apply coupon process seems to work.

Can you guys let me know what is the way to translate sweet alert message please ? I still didn't find ahah

Thanks

**Comment by sicdigital** [comment]
@cboursier -- The sweet alert messages are hard coded. I ended up updating a fork with my text changes. It would be nice to have a setting to change these messages though.

**Comment by cristianraiber** [comment]
@sicdigital - care to open up a PR with your changes? someone will review it and merge it afterwards

**Comment by sicdigital** [comment]
I just hard coded the messages to be more grammatically correct for my use, but it wouldn't be a bad idea to add a setting to override a default for this.

**Comment by cristianraiber** [comment]
@sicdigital - 👍 for that!

**Comment by mokasius** [comment]
Hello, I'm having the same problem with the apply changes button, where can I change the click event? Just to update the page and not go to checkout.
Thanks

**Comment by cristianraiber** [comment]
cc @cristian-e
