### ISSUE TITLE
default currency issue

### ISSUE THREAD

**Issue by pitchourou** [ColorlibHQ/Fashe#3]
the theme is showing EUR as default currency instead of USD even if you change the settings, 
how to fix that ?

THIS THEME REALLY SUCKS buy the way, i spent a lot of time fixing the issues , problem is I started using it and i can't rollback now

**Comment by cristianraiber** [comment]
@cristian-e - please see this one as well

**Comment by cristian-e** [comment]
This doesn't seem to be an issue any longer.

For example using these settings in the `Theme Settings` panel:
![666](https://user-images.githubusercontent.com/43263346/51544306-4d127c80-1e68-11e9-83b3-78d1c339cf2e.PNG)

And again these settings `Settings -> General`:
![dsadad](https://user-images.githubusercontent.com/43263346/51544431-995dbc80-1e68-11e9-8950-d1791db354cc.PNG)

Will show the `USD` currency be default on all products

**Comment by cristianraiber** [comment]
Will close this. @pitchourou - feel free to reply here (after you've downloaded & installed the latest Fashe theme) IF this issue is still happening at your end.
