### ISSUE TITLE
hide variant images for mobile view? & change color swatches to dropdown selector

### ISSUE THREAD

**Issue by se78g** [ColorlibHQ/Fashe#30]
basically what the title says, I'm wondering if there's a way to hide the variant images or at the least make the images not form a long vertical line needing to be scrolled past (on mobile view), and a way to change the color swatch to a dropdown color/type selector. thank you.

**Comment by cristianraiber** [comment]
@cristian-e - please see this

**Comment by se78g** [comment]
any updates?

**Comment by cristian-e** [comment]
Hi.

To hide the variant images on mobile devices, add this custom css code:
```
@media(max-width: 768px) {
	.product-detail-wrap .wrap-slick3-dots {
		display: none;
	}
	.product-detail-wrap #product-image-carousel {
		width: 100%;
	}
}
```
in order for this to work, you must add the `.product-detail-wrap` class in the `product.liquid` file, line 9. Change the line from:
```
<div class="container bgwhite p-t-35 p-b-80">
```
to 
```
<div class="product-detail-wrap container bgwhite p-t-35 p-b-80">
```

To change from color swatches to a select list use the file in this archive:
[swatch.zip](https://github.com/ColorlibHQ/Fashe/files/3203498/swatch.zip)

You need to overwrite the file `swatch.liquid` located in the `snippets` folder of your theme.

The color swatches should be replaced with a select dropdown:
![124](https://user-images.githubusercontent.com/43263346/58112720-bcbd2c00-7bfc-11e9-8196-abb07d6367e8.PNG).

If you have any more questions don't hesitate to ask.

**Comment by se78g** [comment]
Hi, thank you! The swatch part worked but I'm confused on where to add the custom css code on the first part

**Comment by cristian-e** [comment]
You can add the code in the `assets/custom.css` file

**Comment by se78g** [comment]
Ok so everything is all good and working fine now except that selecting a new variant on the product page doesnt change the picture over to the selected variant so the customer can see what it looks like. any fix?

**Comment by cristian-e** [comment]
Hi. 

Make sure you don't have any javascript errors on your page. The changes should work like this:
![u](https://user-images.githubusercontent.com/43263346/58332292-963d0200-7e43-11e9-9372-53198a86793a.gif)

You can post the link to your shop so I can check.

Thanks

**Comment by se78g** [comment]
Here's the link: https://8w5j6mpjxflof46l-9243361358.shopifypreview.com

**Comment by se78g** [comment]
any help? here's the link again: https://7d2p6r77u0n3dd0n-9243361358.shopifypreview.com

**Comment by se78g** [comment]
???

**Comment by cristian-e** [comment]
hi. please send a new link. this one has expired.
