### ISSUE TITLE
Mobile Cart Unclickable when Product is added to Cart

### ISSUE THREAD

**Issue by shahzadmusawwir** [ColorlibHQ/Fashe#5]
When using Fashe on Mobile the cart function doesn’t work i.e, When I add a product into the cart and try to click on the Cart Icon. It is unclickable like an image which doesn’t redirects me anywhere. I am very frustrated and many of my customers have raised an issue about this to me.

**Comment by sicdigital** [comment]
I'm having this same issue when trying to use this theme. I submitted a pull request that fixes the issue. #6
