### ISSUE TITLE
Variation images are not changing

### ISSUE THREAD

**Issue by nodarik** [ColorlibHQ/Fashe#7]
Variations images are not changing on the product page
https://colorlib.com/wp/forums/topic/fashe-theme-variant-image-not-changing/

**Comment by zing0314** [comment]
Hi! Is there a fix already to this problem? I'm having the same problem with my product page.

**Comment by mawahebsaeed** [comment]
Can i change the Mobile Collection Grid to 4 Images on screen instead of scrolling through the products one by one ?

**Comment by cristianraiber** [comment]
This should be fixed here: https://github.com/MachoThemes/Fashe/commit/284817c1f38375b131d1fb79ee9d6fc84458ccdd

After you've downloaded & installed the latest Fashe ZIP, if this issue persists, please comment here and I will re-open the ticket.
