### ISSUE TITLE
Colors not changing

### ISSUE THREAD

**Issue by nodarik** [ColorlibHQ/Fashe#8]
> 
 Whenever I change the color skin, the top bar or the color over the word selected (ex: when I click shop or about us) will not update and change to the color I want. I have tried clearing my browser cache, etc.

https://colorlib.com/wp/forums/topic/colors-not-changing-in-fashe-theme/

**Comment by rhougardy** [comment]
I also have the same problem and it would be perfect if this would be possible to change

**Comment by cristianraiber** [comment]
This has been fixed here: https://github.com/MachoThemes/Fashe/commit/284817c1f38375b131d1fb79ee9d6fc84458ccdd

PLease comment in this ticket (after you've made sure to download & install the latest version of Fashe) if the issue persists.
